#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Appearance (active/inactive borders)
bspc config normal_border_color  "#444444"
bspc config focused_border_color "#8ec07c"

# Cursor theme
export XCURSOR_THEME="WinSur Dark Cursors"
export XCURSOR_SIZE=24
xsetroot -cursor_name left_ptr

# Autostart
sxhkd &
nm-applet &
pulseaudio --start &
picom --experimental-backends --config ~/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &

# Map Caps Lock to Escape
setxkbmap -option caps:escape

# set default volume to 50%
pactl set-sink-volume @DEFAULT_SINK@ 50%



