;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #aa282828
background-alt = #cc373b41
foreground = #ebdbb2
primary = #d79921
secondary = #458588
alert = #cc241d
disabled = #707880

[bar/left]
offset-x = 6
offset-y = 2
width = 678px
height = 24pt
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 2
border-color = ${colors.background-alt}

line-size = 3pt

padding-left = 1
padding-right = 1


module-margin = 1

separator = "\"
separator-foreground = ${colors.disabled}
font-0 = "Berkeley NF:style=Regular:size=14;3"
font-1 = "Berkeley NF:style=Bold:size=14;3"
font-2 = "Weather Icons:style=Regular:size=14;3"
font-3 = "FontAwesome 7 Free:style=Regular:size=12;2"

modules-left = battery workspaces cpu memory temperature updates cava

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = bspwm
dpi=96

[bar/center]
offset-x = 46%
offset-y = 2
width = 8%
height = 24pt
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 2
border-color = ${colors.background-alt}

line-size = 3pt

padding-left = 1
padding-right = 1

module-margin = 1

font-0 = "Berkeley NF:style=Regular:size=14;3"
font-1 = "Berkeley NF:style=Bold:size=14;3"

modules-center = date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = bspwm
dpi = 96

[bar/right]
offset-x = 1234px
offset-y = 2

width = 680px
height = 24pt
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 2
border-color = ${colors.background-alt}

line-size = 10pt

padding-left = 4
padding-right = 2

module-margin = 1

separator = "/"
separator-foreground = ${colors.disabled}
font-0 = "Berkeley NF:style=Regular:size=14;3"
font-1 = "Berkeley NF:style=Bold:size=20;3"
font-2 = "Weather Icons:style=Regular:size=14;3"
font-3 = "Font Awesome 7 Free:style=Regular:size=12;2"

modules-right = pulseaudio brightness bluetooth weather wlan
cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = bspwm
dpi = 96

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
format-charging = <animation-charging> <label-charging>
format-charging-foreground = #8ec07c
format-discharging = <ramp-capacity> <label-discharging>
format-low = <animation-low> <label-low>
format-low-foreground = ${colors.alert}

label-discharging = %percentage%%
label-charging = "%percentage%%"
label-low = %percentage%%

ramp-capacity-0 = 󰁻
ramp-capacity-1 = 󰁾
ramp-capacity-2 = 󰂁
ramp-capacity-3 = 󰁹

low-at = 20

animation-charging-0 = 󰂎
animation-charging-1 = 󰁻
animation-charging-2 = 󰁾
animation-charging-3 = 󰂁
animation-charging-4 = 󰁹
animation-charging-framerate = 600

animation-low-0 = 󰂃
animation-low-1 = 󰂎
animation-low-framerate = 1500

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-font = 4
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = 󰝟 muted
label-muted-foreground = ${colors.disabled}
enable-scroll = true

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 5
format-prefix = " "
format-font = 4
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 5
format-prefix = " "
format-font = 4
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/wlan]
type = internal/network
interface = wlp0s20f3
interval = 5

format-connected = <label-connected> <ramp-signal>
label-connected = "%essid%"
label-connected-foreground = ${colors.foreground}

format-disconnected = <label-disconnected>
format-disconnected-foreground = ${colors.disabled}
label-disconnected = "󰣾 No Signal"

ramp-signal-0 = 󰣴
ramp-signal-1 = 󰣶
ramp-signal-2 = 󰣸
ramp-signal-3 = 󰣺
ramp-signal-font = 4
ramp-signal-foreground = ${colors.primary}

click-left = nm-applet

[module/temperature]
type = internal/temperature
interval = 5
base-temperature = 40
warn-temperature = 80

units = true
format = <ramp> <label>
format-warn = <ramp> <label-warn>

label = %temperature-c%

label-warn = " %temperature-c%"
label-warn-foreground = ${colors.alert}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.primary}

[module/date]
type = internal/date
interval = 1
date = %H:%M:%S
date-alt = %d-%m-%y %H:%M
label = %date%
label-foreground = ${colors.primary}


[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth/bluetooth.sh
interval = 5
click-left = ~/.config/polybar/scripts/bluetooth/toggle_bluetooth.sh

[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather/weather.sh
interval = 500
format = <label>
format-font = 1
label = %output%
label-foreground = ${colors.foreground}

[module/workspaces]
type = internal/bspwm

pin-workspaces = true

format = <label-state> <label-mode>
format-background = ${colors.background-alt}
format-padding = 1

label-focused = %name%
label-focused-background = ${colors.primary}
label-focused-foreground = #282828
label-focused-padding = 1

label-occupied = %name%
label-occupied-foreground = ${colors.foreground}
label-occupied-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

label-separator = ""

click-left = bspc desktop -f {desktop}

[module/brightness]
type = internal/backlight
card = intel_backlight

enable-scroll = true
format-prefix = ""
format-prefix-font = 2
format-prefix-foreground = ${colors.primary}

label = " %percentage%%" 

[module/updates]
type = custom/script
exec = $HOME/.config/polybar/scripts/updates/check_updates.sh
interval = 300
format-prefix = " "
format-prefix-font = 4
format-prefix-foreground = ${colors.primary}
format = <label>
label = %output%
label-foreground = ${colors.foreground}

[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/polybar/scripts/cava/cava.sh
format = <label>
format-font = 5
label = %output%
label-foreground = ${colors.disabled}


[settings]
screenchange-reload = true
pseudo-transparency = false


; vim:ft=dosini